### ISSUE TITLE
dhcp -T not working on docker image based on Alpine 3.17.1

### ISSUE THREAD

**Issue by carlo161** [NetworkConfiguration/dhcpcd#185]
Hello,
I created a docker image based on Alpine to run a DHCP server for my system.
As an healthcheck I run "dhcpcd -T" and everything was fine for two years at least.
Now I upgrade my image to Alpine 3.17.1 and the same command exit with an error: Bad system call (core dumped)
This is the complete output of the command.
```
/ # dhcpcd -T
dhcpcd-9.4.1 starting
DUID 00:04:8a:bc:a6:b3:c9:21:11:e6:9c:43:bc:00:00:ba:00:00
eno1: IAID b5:7b:6d:6f
veth5271379: IAID cf:4d:55:d8
tun0: IAID 74:75:6e:30
tun0: using static address 10.16.0.1/24
interface='tun0'
pid='566'
protocol='dhcp'
reason='TEST'
ifcarrier='up'
ifflags='69841'
ifmetric='1010'
ifmtu='1500'
ifwireless='0'
new_broadcast_address='10.16.0.255'
new_ip_address='10.16.0.1'
new_network_number='10.16.0.0'
new_subnet_cidr='24'
new_subnet_mask='255.255.255.0'
Bad system call (core dumped)
```
If I switch back to Alpine 3.16.2 everything is fine again.
What am I doing wrong? Is there any issue in the newer dhcpcd version?

**Comment by rsmarples** [comment]
This should be fixed in the dhcpcd-9 branch already.

**Comment by carlo161** [comment]
How could I install the newer version? I see on [https://pkgs.alpinelinux.org/package/v3.17/main/x86_64/dhcpcd](https://pkgs.alpinelinux.org/package/v3.17/main/x86_64/dhcpcd) that a newer version was built on 11/02/2023 but if I rebuild my image I still have the issue. If I run `dhcpcd --version` it just return me `9.4.1` without specifying the r2 or r3.

**Comment by rsmarples** [comment]
This is a duplicate of #186

**Comment by carlo161** [comment]
With alpine 3.17.2 everything works fine.
