### ISSUE TITLE
dhcpcd 10.0.4 --enable-privsep fails to fork in the background

### ISSUE THREAD

**Issue by tomalok** [NetworkConfiguration/dhcpcd#260]
Related to https://gitlab.alpinelinux.org/alpine/aports/-/issues/15417 and https://gitlab.alpinelinux.org/alpine/cloud/tiny-cloud/-/issues/48

`dhcpcd` 10.0.4 with `--enable-privsep` fails to fork into the background...
```
 * Starting networking ... *   lo ... [ ok ]
 *   eth0 ...dhcpcd-10.0.4 starting
DUID 00:01:00:01:2c:d2:c9:cf:0a:15:c6:f6:91:91
eth0: IAID c6:f6:91:91
eth0: soliciting an IPv6 router
eth0: Router Advertisement from fe80::8e7:ddff:fe5c:ad3b
eth0: no global addresses for default route
eth0: adding route to 2600:1f14:2a4a:8902::/64
eth0: soliciting a DHCPv6 lease
eth0: soliciting a DHCP lease
eth0: offered 172.30.2.109 from 172.30.2.1
eth0: probing address 172.30.2.109/24
eth0: ADV 2600:1f14:2a4a:8902:55b4:ea04:18cf:3342/128 from fe80::8e7:ddff:fe5c:ad3b
eth0: REPLY6 received from fe80::8e7:ddff:fe5c:ad3b
eth0: adding address 2600:1f14:2a4a:8902:55b4:ea04:18cf:3342/128
eth0: renew in 70, rebind in 112, expire in 450 seconds
eth0: adding default route via fe80::8e7:ddff:fe5c:ad3b
forked to background, child pid 1870
dhcpcd_fork_cb: truncated read 0 (expected 4)
ifup: failed to change interface eth0 state to 'up'
 [ !! ]
```

10.0.3 works, and 10.0.4 without `--enable-privsep` is also working as expected.

**Comment by tomalok** [comment]
Following the commits forward from 10.0.3 towards 10.0.4, https://github.com/NetworkConfiguration/dhcpcd/commit/ac4a70dc89ffd545e7a8c8c07711497376ac85f5 is the commit that first causes the failure.

**Comment by tomalok** [comment]
With all commits between 10.0.3 and 10.0.4 applied, except https://github.com/NetworkConfiguration/dhcpcd/commit/ac4a70dc89ffd545e7a8c8c07711497376ac85f5, the problem does not exist.

Something in https://github.com/NetworkConfiguration/dhcpcd/commit/ac4a70dc89ffd545e7a8c8c07711497376ac85f5 needs to be fixed.

**Comment by tomalok** [comment]
https://github.com/NetworkConfiguration/dhcpcd/blob/2d07224f97592847d8c8743e5a82d99c450c014a/src/dhcpcd.c#L1840

fork callback gets called, but there's no exit code from the fork fd (yet?)

**Comment by skibbipl** [comment]
I think I'm also affected by this bug on my raspberrypi os (trixie). After update of the dhcpcd package on 31.10 I cannot run dhcpcd daemon:
```
lis 03 12:21:15 rpi4b dhcpcd[20875]: dhcpcd-10.0.4 starting
lis 03 12:21:15 rpi4b dhcpcd[20878]: dev: loaded udev
lis 03 12:21:15 rpi4b dhcpcd[20878]: DUID XX:XX:XX
lis 03 12:21:15 rpi4b dhcpcd[20878]: eth0: IAID XX:XX:XX
lis 03 12:21:15 rpi4b dhcpcd[20878]: dhcpcd_prestartinterface: Operation not possible due to RF-kill
lis 03 12:21:15 rpi4b dhcpcd[20878]: wlan0: waiting for carrier
lis 03 12:21:15 rpi4b dhcpcd[20875]: dhcpcd_prestartinterface: Operation not possible due to RF-kill
lis 03 12:21:16 rpi4b dhcpcd[20878]: eth0: soliciting an IPv6 router
lis 03 12:21:16 rpi4b dhcpcd[20878]: eth0: rebinding lease of 192.168.1.4
lis 03 12:21:16 rpi4b dhcpcd[20878]: eth0: leased 192.168.1.4 for 86400 seconds
lis 03 12:21:16 rpi4b dhcpcd[20878]: eth0: adding route to 192.168.1.0/26
lis 03 12:21:16 rpi4b dhcpcd[20878]: eth0: adding default route via 192.168.1.1
lis 03 12:21:16 rpi4b dhcpcd[20875]: dhcpcd_fork_cb: truncated read 0 (expected 4)
```

**Comment by tomalok** [comment]
reverting https://github.com/NetworkConfiguration/dhcpcd/commit/ac4a70dc89ffd545e7a8c8c07711497376ac85f5#diff-5ba67626cc214a1de027b4cc749baea8e9473a60a89ff3cf5bb6b2b48137dd73R1895-R1911 fixes the problem, but if i'm reading it right, the patch ***DOES*** what's intended, setting a file descriptor to /dev/null.

Maybe a file descriptor is getting reset to /dev/null too soon to report back?

**Comment by tomalok** [comment]
leaving `dup_null()` patched as in 10.0.4, but reverting https://github.com/NetworkConfiguration/dhcpcd/commit/ac4a70dc89ffd545e7a8c8c07711497376ac85f5#diff-5ba67626cc214a1de027b4cc749baea8e9473a60a89ff3cf5bb6b2b48137dd73R2012-R2026 also fixes the problem.

This might be the source of the over-eager /dev/null-ing of file descriptors (or it's happening before `dhcpcd_fork_cb` gets its return value).

**Comment by perkelix** [comment]
@rsmarples it seems that 10.0.4 might have introduced a regression when running in daemon mode.

**Comment by tomalok** [comment]
The system I was using to dig into this suddenly started working again (x86_64), so I'm not 100% sure of my last two comments, because I'm unable to reproduce there at this time -- it _might_ be a race condition whereby sometimes the expected value does make it through before the fd's /dev/null'd?

This is more "reliably" not working on aarch64, I'll need to switch my dev environment to continue digging.

**Comment by tomalok** [comment]
with `-d` output
```
dhcpcd-10.0.4 starting
chrooting as dhcpcd to /var/lib/dhcpcd
sandbox: seccomp
spawned manager process on PID 3038
spawned privileged proxy on PID 3039
spawned network proxy on PID 3040
spawned controller proxy on PID 3041
DUID 00:01:00:01:2c:d8:12:68:0a:52:3a:c8:94:9d
eth0: spawned DHCP6 proxy 2600:1f14:2a4a:8902:5b99:c8c0:9d18:96b2 on PID 3044
eth0: spawned DHCP6 proxy fe80::852:3aff:fec8:949d on PID 3045
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks PREINIT
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks CARRIER
eth0: IAID 3a:c8:94:9d
eth0: delaying IPv6 router solicitation for 0.2 seconds
eth0: delaying IPv4 for 1.4 seconds
eth0: soliciting an IPv6 router
eth0: sending Router Solicitation
eth0: Router Advertisement from fe80::8e7:ddff:fe5c:ad3b
eth0: adding route to 2600:1f14:2a4a:8902::/64
eth0: adding default route via fe80::8e7:ddff:fe5c:ad3b
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks ROUTERADVERT
eth0: reading lease: /var/lib/dhcpcd/eth0.lease6
eth0: confirming prior DHCPv6 lease
eth0: delaying CONFIRM6 (xid 0x813f86), next in 1.0 seconds
eth0: multicasting CONFIRM6 (xid 0x813f86), next in 1.1 seconds
eth0: REPLY6 received from fe80::8e7:ddff:fe5c:ad3b
eth0: adding address 2600:1f14:2a4a:8902:5b99:c8c0:9d18:96b2/128
eth0: pltime 140 seconds, vltime 450 seconds
eth0: sending NA for 2600:1f14:2a4a:8902:5b99:c8c0:9d18:96b2/128
eth0: renew in 0, rebind in 2, expire in 340 seconds
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks REBOOT6
forked to background, child pid 3038
dhcpcd_fork_cb: truncated read 0 (expected 4)
```

**Comment by tomalok** [comment]
after some more testing in an environment that more reliably exhibits the problem (aarch64) I've narrowed it down to https://github.com/NetworkConfiguration/dhcpcd/commit/ac4a70dc89ffd545e7a8c8c07711497376ac85f5#diff-5ba67626cc214a1de027b4cc749baea8e9473a60a89ff3cf5bb6b2b48137dd73R355-R356

with these two `dup2()` commented out the truncated read no longer happens.

commenting out just one or the other still results in a truncated read.

**Comment by rsmarples** [comment]
Can the people here please test the branch/commit I added above and let me know if that fixes it for you all?

**Comment by skibbipl** [comment]
I suck at compiling stuff for linux, but I forked the code and build a new dhcpcd binary. Still not working:
```
lis 08 11:33:34 rpi4b dhcpcd[341082]: dhcpcd-10.0.4 starting
lis 08 11:33:34 rpi4b dhcpcd[341082]: dhcpcd_fork_cb: zero read
```

**Comment by rsmarples** [comment]
@skibbipl I force pushed a slightly different patch.
If that still fails, please post how you compiled and the options you started dhcpcd with.
Also, please add the debug option to `/etc/dhcpcd.conf`.

**Comment by skibbipl** [comment]
Still no luck. I build the binary by installing dev libraries and using `./configure` and then `make`.
```
lis 08 15:00:46 rpi4b dhcpcd[352660]: main: mkdir: /var/db/dhcpcd: No such file or directory
lis 08 15:00:46 rpi4b dhcpcd[352660]: main: mkdir: /var/db/dhcpcd: No such file or directory
lis 08 15:00:46 rpi4b dhcpcd[352660]: dhcpcd-10.0.4 starting
lis 08 15:00:46 rpi4b dhcpcd[352660]: dhcpcd-10.0.4 starting
lis 08 15:00:46 rpi4b dhcpcd[352660]: chrooting as dhcpcd to /usr/lib/dhcpcd
lis 08 15:00:46 rpi4b dhcpcd[352662]: spawned manager process on PID 352662
lis 08 15:00:46 rpi4b dhcpcd[352660]: chrooting as dhcpcd to /usr/lib/dhcpcd
lis 08 15:00:46 rpi4b dhcpcd[352660]: sandbox: seccomp
lis 08 15:00:46 rpi4b dhcpcd[352660]: spawned manager process on PID 352662
lis 08 15:00:46 rpi4b dhcpcd[352663]: dev: /lib/dhcpcd/dev: No such file or directory
lis 08 15:00:46 rpi4b dhcpcd[352663]: spawned privileged proxy on PID 352663
lis 08 15:00:46 rpi4b dhcpcd[352660]: dev: /lib/dhcpcd/dev: No such file or directory
lis 08 15:00:46 rpi4b dhcpcd[352660]: spawned privileged proxy on PID 352663
lis 08 15:00:46 rpi4b dhcpcd[352660]: dhcpcd_fork_cb: dhcpcd manager hungup
```

**Comment by rsmarples** [comment]
@skibbipl heh, that's a different error! Caused by not using the same compile flags, but don't panic I've just pushed a fix to the branch for that. It should be good now :)

`dev: /lib/dhcpcd/dev: No such file or directory` will no longer cause dhcpcd to abort.

**Comment by tomalok** [comment]
@rsmarples do you have a link to that branch?  (the commit link above does not seem to have your latest updates?)

a diff from the 10.0.4 release tag to that branch would also make my life (a little) easier.  ;)

**Comment by tomalok** [comment]
found https://github.com/NetworkConfiguration/dhcpcd/commits/fix_fork_cb

**Comment by rsmarples** [comment]
@tomalok you'll need to enable debug in `/etc/dhcpcd.conf` and look at the kernel logs to see if that logged a dhcpcd crash.
I cut the above branch on Alpine-3.18.2

**Comment by skibbipl** [comment]
I've recompiled again, but still no luck. Maybe I'm building it wrongly or there are different direcotories used in debian :(
Logs: https://pastebin.com/mvZqRdzC

**Comment by rsmarples** [comment]
@skibbipl aha! kernel shows this: `kernel: audit: type=1326 audit(1699510300.029:13): auid=4294967295 uid=117 gid=65534 ses=4294967295 pid=399289 comm="dhcpcd" exe="/usr/sbin/dhcpcd" sig=31 arch=c00000b7 syscall=24 compat=0>`

**Comment by skibbipl** [comment]
Still no luck...
https://pastebin.com/zptkhzpP

**Comment by rsmarples** [comment]
@skibbipl aha! You're using aarch64, not x86_64 - I got the wrong syscall!
Now it makes sense - your libc is making the dup3 syscall rather than dup2 which is what dhcpcd uses.
Patched in 6a36f96740f8fb9f9b615b157962505f1ad8a00c
I pulled the yield one so you might need to discard your local branch.

**Comment by skibbipl** [comment]
The issue is fixed on my end! 🎉
And sorry, I didn't emphasize enough that I use dhcpcd on my raspberrypi.

**Comment by rsmarples** [comment]
No worries!

@tomalok I don't suppose this fixes it for you as well?

**Comment by tomalok** [comment]
```
i-0cda98b8fabad2c07:~$ doas dhcpcd eth0
dhcpcd-10.0.4 starting
chrooting as dhcpcd to /var/lib/dhcpcd
sandbox: seccomp
spawned manager process on PID 8506
spawned privileged proxy on PID 8507
spawned network proxy on PID 8508
spawned controller proxy on PID 8509
DUID 00:01:00:01:2c:de:ea:a0:0a:f7:84:ef:29:a9
eth0: spawned DHCP6 proxy 2600:1f14:2a4a:8902:ba64:e9dc:cf70:8c97 on PID 8512
eth0: spawned DHCP6 proxy fe80::8f7:84ff:feef:29a9 on PID 8513
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks PREINIT
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks CARRIER
eth0: IAID 84:ef:29:a9
eth0: delaying IPv6 router solicitation for 0.9 seconds
eth0: delaying IPv4 for 1.9 seconds
eth0: soliciting an IPv6 router
eth0: sending Router Solicitation
eth0: Router Advertisement from fe80::8e7:ddff:fe5c:ad3b
eth0: adding route to 2600:1f14:2a4a:8902::/64
eth0: adding default route via fe80::8e7:ddff:fe5c:ad3b
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks ROUTERADVERT
eth0: reading lease: /var/lib/dhcpcd/eth0.lease6
eth0: confirming prior DHCPv6 lease
eth0: delaying CONFIRM6 (xid 0xee9553), next in 1.0 seconds
eth0: reading lease: /var/lib/dhcpcd/eth0.lease
eth0: rebinding lease of 172.30.2.47
eth0: spawned BPF ARP 172.30.2.47 on PID 8533
eth0: ARP announcing 172.30.2.47 (1 of 2), next in 2.0 seconds
eth0: sending REQUEST (xid 0xeedd59db), next in 4.0 seconds
eth0: spawned BPF BOOTP on PID 8534
eth0: acknowledged 172.30.2.47 from 172.30.2.1
eth0: leased 172.30.2.47 for 3600 seconds
eth0: renew in 1800 seconds, rebind in 3150 seconds
eth0: writing lease: /var/lib/dhcpcd/eth0.lease
eth0: adding IP address 172.30.2.47/24 broadcast 172.30.2.255
eth0: adding route to 172.30.2.0/24
eth0: adding default route via 172.30.2.1
eth0: ARP announcing 172.30.2.47 (1 of 2), next in 2.0 seconds
eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks REBOOT
forked to background
```

```
i-0cda98b8fabad2c07:~$ ps wwaxuf|grep dhcpcd
 8506 dhcpcd    0:00 dhcpcd: eth0 [ip4] [ip6]
 8507 root      0:00 dhcpcd: [privileged proxy] eth0 [ip4] [ip6]
 8508 dhcpcd    0:00 dhcpcd: [network proxy] eth0 [ip4] [ip6]
 8509 dhcpcd    0:00 dhcpcd: [control proxy] eth0 [ip4] [ip6]
 8512 dhcpcd    0:00 dhcpcd: [DHCP6 proxy] 2600:1f14:2a4a:8902:ba64:e9dc:cf70:8c97
 8513 dhcpcd    0:00 dhcpcd: [DHCP6 proxy] fe80::8f7:84ff:feef:29a9
 8533 dhcpcd    0:00 dhcpcd: [BPF ARP] eth0 172.30.2.47
 8556 dhcpcd    0:00 dhcpcd: [BOOTP proxy] 172.30.2.47
 8682 alpine    0:00 grep dhcpcd
```

@rsmarples looks good here! -- do you happen to know when we might see a new `dhcpcd` release?  Alpine Linux is getting close to releasing 3.19.0 soon, and although we could just patch from 10.0.4 release, it'd be nice to have an official 10.0.5...  ;)

**Comment by rsmarples** [comment]
> @rsmarples looks good here! -- do you happen to know when we might see a new `dhcpcd` release? Alpine Linux is getting close to releasing 3.19.0 soon, and although we could just patch from 10.0.4 release, it'd be nice to have an official 10.0.5... ;)

dhcpcd-10.0.5 is out :)
